spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka 

zuul:
  routes:
    item-service: /item-service/**
    order-service: /order-service/**
    user-service: /user-service/**
    
  retryable: true